# Generated by Django 5.2.17 on 2026-10-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('code', models.CharField(max_length=50, verbose_name='Mã hợp đồng / Contract Code')),
                ('delivery_status', models.CharField(choices=[('pending', 'Chưa giao / Pending'), ('delivered', 'Đã giao / Delivered')], default='pending', max_length=20, verbose_name='Tình trạng giao hàng / Delivery Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Hợp đồng / Contract',
                'verbose_name_plural': 'Hợp đồng / Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('item_type', models.CharField(max_length=100, verbose_name='Loại hàng / Item Type')),
                ('spec', models.TextField(blank=True, null=True, verbose_name='Cấu hình / Specification')),
                ('qty_ordered', models.PositiveIntegerField(verbose_name='Số lượng đặt / Ordered Qty')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contract', verbose_name='Hợp đồng / Contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Dòng hàng hợp đồng / Contract Line',
                'verbose_name_plural': 'Dòng hàng hợp đồng / Contract Lines',
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_contract_code'),
        ),
    ]
