"""initial schema

Revision ID: 78091702b716
Revises: 
Create Date: 2026-10-06 16:05:48.762397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('preferred_lang', sa.String(length=5), server_default=sa.text("'en'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("preferred_lang IN ('en', 'ja', 'vi')", name=op.f('ck_users_lang_allowed')),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_users_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_users_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_users_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index('uq_alive_users_username', 'users', ['username'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('access_cards',
    sa.Column('card_no', sa.String(length=50), nullable=False),
    sa.Column('card_type', sa.Enum('STAFF', 'CONTRACTOR', 'GUEST', name='card_type'), server_default=sa.text("'CONTRACTOR'"), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'BORROWED', 'LOST', 'DAMAGED', name='card_status'), server_default=sa.text("'IN_STOCK'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_access_cards_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_access_cards_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_access_cards_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_access_cards_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_cards'))
    )
    op.create_index(op.f('ix_access_cards_is_deleted'), 'access_cards', ['is_deleted'], unique=False)
    op.create_index('uq_alive_access_cards_card_no', 'access_cards', ['card_no'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('asset_categories',
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_asset_categories_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_asset_categories_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_asset_categories_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_asset_categories_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_categories'))
    )
    op.create_index(op.f('ix_asset_categories_is_deleted'), 'asset_categories', ['is_deleted'], unique=False)
    op.create_index('uq_alive_asset_categories_name_en', 'asset_categories', ['name_en'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('asset_tags',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_asset_tags_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_asset_tags_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_asset_tags_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_asset_tags_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_tags'))
    )
    op.create_index(op.f('ix_asset_tags_is_deleted'), 'asset_tags', ['is_deleted'], unique=False)
    op.create_index('uq_alive_asset_tags_code', 'asset_tags', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'LOGIN', 'LOGIN_FAIL', 'REVEAL', name='audit_action'), nullable=False),
    sa.Column('before_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('contracts',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), server_default=sa.text("'KDDI Vietnam'"), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', name='delivery_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_contracts_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_contracts_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_contracts_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_contracts_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_is_deleted'), 'contracts', ['is_deleted'], unique=False)
    op.create_index('uq_alive_contracts_code', 'contracts', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('departments',
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_departments_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_departments_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_departments_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_departments_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index('uq_alive_departments_code', 'departments', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false AND code IS NOT NULL'))
    op.create_index('uq_alive_departments_name_en', 'departments', ['name_en'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('license_products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.Enum('PERPETUAL', 'SUBSCRIPTION', name='license_type'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_license_products_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_license_products_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_license_products_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_license_products_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_products'))
    )
    op.create_index(op.f('ix_license_products_is_deleted'), 'license_products', ['is_deleted'], unique=False)
    op.create_index('uq_alive_license_products_name', 'license_products', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('locations',
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('room_en', sa.String(length=100), nullable=False),
    sa.Column('room_ja', sa.String(length=100), nullable=True),
    sa.Column('is_access_controlled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_locations_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_locations_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_locations_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_locations_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index('uq_alive_locations_building_floor_room_en', 'locations', ['building', 'floor', 'room_en'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('roles',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_roles_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_roles_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_roles_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_roles_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index('uq_alive_roles_code', 'roles', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("action IN ('view', 'add', 'change', 'delete')", name=op.f('ck_user_permission_overrides_action_allowed')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permission_overrides_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_overrides')),
    sa.UniqueConstraint('user_id', 'module', 'action', name=op.f('uq_user_permission_overrides_user_id_module_action'))
    )
    op.create_table('access_card_locations',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['access_cards.id'], name=op.f('fk_access_card_locations_card_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_access_card_locations_location_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('card_id', 'location_id', name=op.f('pk_access_card_locations'))
    )
    op.create_table('contract_lines',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_contract_lines_soft_delete_coherent')),
    sa.CheckConstraint('qty_ordered > 0', name=op.f('ck_contract_lines_qty_positive')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_contract_lines_contract_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_contract_lines_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_contract_lines_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_contract_lines_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_lines'))
    )
    op.create_index(op.f('ix_contract_lines_is_deleted'), 'contract_lines', ['is_deleted'], unique=False)
    op.create_table('licenses',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('license_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_licenses_soft_delete_coherent')),
    sa.CheckConstraint('expiry_date IS NULL OR start_date IS NULL OR expiry_date >= start_date', name=op.f('ck_licenses_expiry_after_start')),
    sa.CheckConstraint('seats > 0', name=op.f('ck_licenses_seats_positive')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_licenses_contract_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_licenses_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_licenses_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['license_products.id'], name=op.f('fk_licenses_product_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_licenses_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_index(op.f('ix_licenses_is_deleted'), 'licenses', ['is_deleted'], unique=False)
    op.create_table('persons',
    sa.Column('staff_code', sa.String(length=50), nullable=False),
    sa.Column('user_login_id', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'RESIGNED', name='person_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('start_working_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_persons_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_persons_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_persons_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_persons_department_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_persons_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index('ix_persons_full_name', 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_is_deleted'), 'persons', ['is_deleted'], unique=False)
    op.create_index('uq_alive_persons_email', 'persons', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false AND email IS NOT NULL'))
    op.create_index('uq_alive_persons_staff_code', 'persons', ['staff_code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_alive_persons_user_login_id', 'persons', ['user_login_id'], unique=True, postgresql_where=sa.text('is_deleted = false AND user_login_id IS NOT NULL'))
    op.create_table('phones',
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.Enum('IP_PHONE', 'DECT_STATION', 'PBX', 'WIFI_PHONE', name='phone_device_type'), nullable=False),
    sa.Column('extension_number', sa.String(length=10), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("extension_number IS NULL OR extension_number <> 'N/A'", name=op.f('ck_phones_no_na_literal')),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_phones_soft_delete_coherent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_phones_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_phones_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_phones_location_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_phones_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phones'))
    )
    op.create_index(op.f('ix_phones_is_deleted'), 'phones', ['is_deleted'], unique=False)
    op.create_index('uq_alive_phones_device_name', 'phones', ['device_name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_alive_phones_extension_number', 'phones', ['extension_number'], unique=True, postgresql_where=sa.text('is_deleted = false AND extension_number IS NOT NULL'))
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.CheckConstraint("action IN ('view', 'add', 'change', 'delete')", name=op.f('ck_role_permissions_action_allowed')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'module', 'action', name=op.f('uq_role_permissions_role_id_module_action'))
    )
    op.create_table('assets',
    sa.Column('asset_code', sa.String(length=50), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('contract_line_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('form_factor', sa.String(length=30), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('hwid', sa.String(length=100), nullable=True),
    sa.Column('mac_ethernet', sa.String(length=20), nullable=True),
    sa.Column('mac_wifi', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'IN_USE', 'REPAIR', 'DISPOSED', 'LOST', name='asset_status'), server_default=sa.text("'IN_STOCK'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_assets_soft_delete_coherent')),
    sa.CheckConstraint('asset_code IS NOT NULL OR vendor_code IS NOT NULL OR serial IS NOT NULL', name=op.f('ck_assets_has_some_identifier')),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], name=op.f('fk_assets_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_line_id'], ['contract_lines.id'], name=op.f('fk_assets_contract_line_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assets_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_assets_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_assets_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index('ix_assets_hwid', 'assets', ['hwid'], unique=False)
    op.create_index(op.f('ix_assets_is_deleted'), 'assets', ['is_deleted'], unique=False)
    op.create_index('ix_assets_mac_ethernet', 'assets', ['mac_ethernet'], unique=False)
    op.create_index('ix_assets_mac_wifi', 'assets', ['mac_wifi'], unique=False)
    op.create_index('uq_alive_assets_asset_code', 'assets', ['asset_code'], unique=True, postgresql_where=sa.text('is_deleted = false AND asset_code IS NOT NULL'))
    op.create_index('uq_alive_assets_serial', 'assets', ['serial'], unique=True, postgresql_where=sa.text('is_deleted = false AND serial IS NOT NULL'))
    op.create_index('uq_alive_assets_vendor_code', 'assets', ['vendor_code'], unique=True, postgresql_where=sa.text('is_deleted = false AND vendor_code IS NOT NULL'))
    op.create_table('card_loans',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('external_name', sa.String(length=100), nullable=True),
    sa.Column('external_company', sa.String(length=150), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('borrowed_at', sa.Date(), nullable=False),
    sa.Column('expected_return_at', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_card_loans_soft_delete_coherent')),
    sa.CheckConstraint('expected_return_at IS NULL OR expected_return_at >= borrowed_at', name=op.f('ck_card_loans_expected_after_borrowed')),
    sa.CheckConstraint('person_id IS NOT NULL OR (external_name IS NOT NULL AND length(btrim(external_name)) > 0)', name=op.f('ck_card_loans_borrower_required')),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= borrowed_at', name=op.f('ck_card_loans_returned_after_borrowed')),
    sa.ForeignKeyConstraint(['card_id'], ['access_cards.id'], name=op.f('fk_card_loans_card_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_card_loans_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_card_loans_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_card_loans_person_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_card_loans_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_loans'))
    )
    op.create_index(op.f('ix_card_loans_is_deleted'), 'card_loans', ['is_deleted'], unique=False)
    op.create_index('uq_open_card_loans_card_id', 'card_loans', ['card_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL AND is_deleted = false'))
    op.create_table('person_secrets',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('pc_password_enc', sa.LargeBinary(), nullable=True),
    sa.Column('pc_password_note', sa.String(length=200), nullable=True),
    sa.Column('email_password_enc', sa.LargeBinary(), nullable=True),
    sa.Column('email_password_note', sa.String(length=200), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_secrets_person_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_person_secrets_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_person_secrets'))
    )
    op.create_table('asset_tag_links',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_tag_links_asset_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['asset_tags.id'], name=op.f('fk_asset_tag_links_tag_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id', name=op.f('pk_asset_tag_links'))
    )
    op.create_table('assignments',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_at', sa.Date(), nullable=False),
    sa.Column('returned_at', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_assignments_soft_delete_coherent')),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= borrowed_at', name=op.f('ck_assignments_returned_after_borrowed')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_assignments_asset_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assignments_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_assignments_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_assignments_person_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_assignments_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index(op.f('ix_assignments_is_deleted'), 'assignments', ['is_deleted'], unique=False)
    op.create_index('uq_open_assignments_asset_id', 'assignments', ['asset_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL AND is_deleted = false'))
    op.create_table('license_assignments',
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=300), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_deleted = false AND deleted_at IS NULL AND delete_reason IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND delete_reason IS NOT NULL AND length(btrim(delete_reason)) > 0)', name=op.f('ck_license_assignments_soft_delete_coherent')),
    sa.CheckConstraint('asset_id IS NOT NULL OR person_id IS NOT NULL', name=op.f('ck_license_assignments_target_required')),
    sa.CheckConstraint('removed_at IS NULL OR removed_at >= assigned_at', name=op.f('ck_license_assignments_removed_after_assigned')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_license_assignments_asset_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_license_assignments_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_license_assignments_deleted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_license_assignments_license_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_license_assignments_person_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_license_assignments_updated_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_assignments'))
    )
    op.create_index(op.f('ix_license_assignments_is_deleted'), 'license_assignments', ['is_deleted'], unique=False)
    op.create_index('uq_open_license_assignments_license_id_asset_id', 'license_assignments', ['license_id', 'asset_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL AND is_deleted = false AND asset_id IS NOT NULL'))
    op.create_index('uq_open_license_assignments_license_id_person_id', 'license_assignments', ['license_id', 'person_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL AND is_deleted = false AND person_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_open_license_assignments_license_id_person_id', table_name='license_assignments', postgresql_where=sa.text('removed_at IS NULL AND is_deleted = false AND person_id IS NOT NULL'))
    op.drop_index('uq_open_license_assignments_license_id_asset_id', table_name='license_assignments', postgresql_where=sa.text('removed_at IS NULL AND is_deleted = false AND asset_id IS NOT NULL'))
    op.drop_index(op.f('ix_license_assignments_is_deleted'), table_name='license_assignments')
    op.drop_table('license_assignments')
    op.drop_index('uq_open_assignments_asset_id', table_name='assignments', postgresql_where=sa.text('returned_at IS NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_assignments_is_deleted'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('asset_tag_links')
    op.drop_table('person_secrets')
    op.drop_index('uq_open_card_loans_card_id', table_name='card_loans', postgresql_where=sa.text('returned_at IS NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_card_loans_is_deleted'), table_name='card_loans')
    op.drop_table('card_loans')
    op.drop_index('uq_alive_assets_vendor_code', table_name='assets', postgresql_where=sa.text('is_deleted = false AND vendor_code IS NOT NULL'))
    op.drop_index('uq_alive_assets_serial', table_name='assets', postgresql_where=sa.text('is_deleted = false AND serial IS NOT NULL'))
    op.drop_index('uq_alive_assets_asset_code', table_name='assets', postgresql_where=sa.text('is_deleted = false AND asset_code IS NOT NULL'))
    op.drop_index('ix_assets_mac_wifi', table_name='assets')
    op.drop_index('ix_assets_mac_ethernet', table_name='assets')
    op.drop_index(op.f('ix_assets_is_deleted'), table_name='assets')
    op.drop_index('ix_assets_hwid', table_name='assets')
    op.drop_table('assets')
    op.drop_table('role_permissions')
    op.drop_index('uq_alive_phones_extension_number', table_name='phones', postgresql_where=sa.text('is_deleted = false AND extension_number IS NOT NULL'))
    op.drop_index('uq_alive_phones_device_name', table_name='phones', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_phones_is_deleted'), table_name='phones')
    op.drop_table('phones')
    op.drop_index('uq_alive_persons_user_login_id', table_name='persons', postgresql_where=sa.text('is_deleted = false AND user_login_id IS NOT NULL'))
    op.drop_index('uq_alive_persons_staff_code', table_name='persons', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_alive_persons_email', table_name='persons', postgresql_where=sa.text('is_deleted = false AND email IS NOT NULL'))
    op.drop_index(op.f('ix_persons_is_deleted'), table_name='persons')
    op.drop_index('ix_persons_full_name', table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_licenses_is_deleted'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_contract_lines_is_deleted'), table_name='contract_lines')
    op.drop_table('contract_lines')
    op.drop_table('access_card_locations')
    op.drop_table('user_permission_overrides')
    op.drop_index('uq_alive_roles_code', table_name='roles', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('uq_alive_locations_building_floor_room_en', table_name='locations', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('uq_alive_license_products_name', table_name='license_products', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_license_products_is_deleted'), table_name='license_products')
    op.drop_table('license_products')
    op.drop_index('uq_alive_departments_name_en', table_name='departments', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_alive_departments_code', table_name='departments', postgresql_where=sa.text('is_deleted = false AND code IS NOT NULL'))
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_table('departments')
    op.drop_index('uq_alive_contracts_code', table_name='contracts', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_contracts_is_deleted'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_table_record', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_alive_asset_tags_code', table_name='asset_tags', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_asset_tags_is_deleted'), table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index('uq_alive_asset_categories_name_en', table_name='asset_categories', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_asset_categories_is_deleted'), table_name='asset_categories')
    op.drop_table('asset_categories')
    op.drop_index('uq_alive_access_cards_card_no', table_name='access_cards', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_access_cards_is_deleted'), table_name='access_cards')
    op.drop_table('access_cards')
    op.drop_index('uq_alive_users_username', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
