# Generated by Django 5.2.17 on 2026-10-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('card_no', models.CharField(max_length=50, verbose_name='Số thẻ in trên thẻ / Card Number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Thẻ ra vào / Access Card',
                'verbose_name_plural': 'Thẻ ra vào / Access Cards',
            },
        ),
        migrations.CreateModel(
            name='CardLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('external_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người ngoài / External Borrower Name')),
                ('external_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Công ty đối tác / External Company')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mục đích mượn / Purpose')),
                ('borrowed_at', models.DateField(verbose_name='Ngày mượn / Borrowed Date')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Ngày trả / Returned Date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='cards.accesscard', verbose_name='Thẻ mượn / Card')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_loans', to='organization.person', verbose_name='Nhân viên mượn / Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Mượn thẻ / Card Loan',
                'verbose_name_plural': 'Lịch sử Mượn thẻ / Card Loans',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng / Room Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Phòng kiểm soát / Room',
                'verbose_name_plural': 'Danh mục Phòng / Rooms',
            },
        ),
        migrations.CreateModel(
            name='AccessCardRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.accesscard', verbose_name='Thẻ / Card')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.room', verbose_name='Phòng / Room')),
            ],
            options={
                'verbose_name': 'Quyền phòng thẻ / Card Room Access',
                'verbose_name_plural': 'Quyền phòng thẻ / Card Room Accesses',
            },
        ),
        migrations.AddField(
            model_name='accesscard',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cards.AccessCardRoom', to='cards.room', verbose_name='Phòng được phép vào / Allowed Rooms'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_room_name'),
        ),
        migrations.AddConstraint(
            model_name='accesscardroom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('card', 'room'), name='unique_active_card_room'),
        ),
        migrations.AddConstraint(
            model_name='accesscard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('card_no',), name='unique_active_card_no'),
        ),
    ]
