# Generated by Django 5.2.17 on 2026-10-05 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('name', models.CharField(max_length=50, verbose_name='Tên loại thiết bị / Category Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Loại thiết bị / Asset Category',
                'verbose_name_plural': 'Loại thiết bị / Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('asset_code', models.CharField(max_length=50, verbose_name='Mã tài sản / Asset Code')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Model thiết bị / Model')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số Serial / Serial Number')),
                ('hwid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã phần cứng / HWID')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ MAC / MAC Address')),
                ('status', models.CharField(choices=[('in_stock', 'Trong kho / In Stock'), ('loaned', 'Đang mượn / Loaned'), ('lost', 'Mất / Lost')], default='in_stock', max_length=20, verbose_name='Trạng thái / Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú / Note')),
                ('contract_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='contracts.contractline', verbose_name='Dòng hợp đồng mua / Contract Line')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Loại thiết bị / Category')),
            ],
            options={
                'verbose_name': 'Tài sản / Asset',
                'verbose_name_plural': 'Tài sản / Assets',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('borrowed_at', models.DateField(verbose_name='Ngày bắt đầu mượn / Borrowed Date')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Ngày trả / Returned Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú / Note')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset', verbose_name='Thiết bị / Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.person', verbose_name='Người mượn / Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Mượn - Trả thiết bị / Asset Assignment',
                'verbose_name_plural': 'Lịch sử Mượn - Trả / Asset Assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_asset_category_name'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('asset_code',), name='unique_active_asset_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('serial', ''), _negated=True)), fields=('serial',), name='unique_active_asset_serial'),
        ),
    ]
