# Generated by Django 5.2.17 on 2026-10-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('name_en', models.CharField(max_length=100, verbose_name='Tên tiếng Anh / English Name')),
                ('name_ja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Nhật / Japanese Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Phòng ban / Department',
                'verbose_name_plural': 'Phòng ban / Departments',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('staff_code', models.CharField(max_length=50, verbose_name='Mã nhân viên / Staff Code')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên / Full Name')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc / Active'), ('resigned', 'Đã nghỉ việc / Resigned')], default='active', max_length=20, verbose_name='Trạng thái / Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.department', verbose_name='Phòng ban / Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Nhân viên / Person',
                'verbose_name_plural': 'Nhân viên / Persons',
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name_en',), name='unique_active_department_name_en'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('staff_code',), name='unique_active_staff_code'),
        ),
    ]
