# Generated by Django 5.2.17 on 2026-10-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Số lượng bản quyền (Seats) / Total Seats')),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã bản quyền / License Key')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu / Start Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn / Expiry Date (Để trống nếu Vĩnh viễn)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Gói License / License',
                'verbose_name_plural': 'Gói License / Licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('assigned_at', models.DateField(verbose_name='Ngày gán / Assigned Date')),
                ('removed_at', models.DateField(blank=True, null=True, verbose_name='Ngày gỡ / Removed Date')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='assets.asset', verbose_name='Thiết bị / Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='licenses.license', verbose_name='Gói License / License')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='organization.person', verbose_name='Người dùng / Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Gán License / License Assignment',
                'verbose_name_plural': 'Lịch sử Gán License / License Assignments',
            },
        ),
        migrations.CreateModel(
            name='LicenseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa gần nhất')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('delete_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phần mềm / Software Product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Phần mềm bản quyền / License Product',
                'verbose_name_plural': 'Danh mục Phần mềm / License Products',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licenses.licenseproduct', verbose_name='Phần mềm / Product'),
        ),
        migrations.AddConstraint(
            model_name='licenseproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_license_product_name'),
        ),
    ]
